// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjcwwvjvqtgjwrnobqwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqY3d3dmp2cXRnandybm9icXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTc1NjksImV4cCI6MjA2NTQ3MzU2OX0.AQUE-TD2_NqmyU90SMiPiK4aLfd_l_ojen92Qn8YT78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);