name: Deploy Supabase SQL Migration

on:
  push:
    paths:
      - 'supabase/migrations/**.sql'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase-linux-amd64.tar.gz | tar -xz
          sudo mv supabase /usr/local/bin/

      - name: Set up Supabase access
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID --token $SUPABASE_ACCESS_TOKEN

      - name: Apply SQL migrations
        run: |
          supabase db push
